package cerror

const CODE_SENT = "CODE_SENT"

const UNSUPPORTED_FORMAT = "UNSUPPORTED_FORMAT"

const INVALID_PASSWORD = "INVALID_PASSWORD"

const PHONE_USED = "PHONE_USED"

const SMS_SERVICE_BAD = "SMS_SERVICE_BAD"

const USERNAME_INVALID = "USERNAME_INVALID"

const PASSWORD_TOO_SHORT = "PASSWORD_TOO_SHORT"
